// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUQXkrMtpkfejZTWYbH8LW9BPWw6EVhY',
    appId: '1:1098062801138:web:401f4c533a14c5faaf086b',
    messagingSenderId: '1098062801138',
    projectId: 'dcm-2-c9eb2',
    authDomain: 'dcm-2-c9eb2.firebaseapp.com',
    storageBucket: 'dcm-2-c9eb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNeo0QiAH5SXdRsZ1AIRHUAc2sZ2HA44o',
    appId: '1:1098062801138:android:7026121b46bba0f5af086b',
    messagingSenderId: '1098062801138',
    projectId: 'dcm-2-c9eb2',
    storageBucket: 'dcm-2-c9eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWda7mD-tbHIUCx9hOHGolQW5qnEPgA04',
    appId: '1:1098062801138:ios:26a6989b67b3c5f1af086b',
    messagingSenderId: '1098062801138',
    projectId: 'dcm-2-c9eb2',
    storageBucket: 'dcm-2-c9eb2.appspot.com',
    iosBundleId: 'com.dcm.dcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWda7mD-tbHIUCx9hOHGolQW5qnEPgA04',
    appId: '1:1098062801138:ios:01d059d74b6345a0af086b',
    messagingSenderId: '1098062801138',
    projectId: 'dcm-2-c9eb2',
    storageBucket: 'dcm-2-c9eb2.appspot.com',
    iosBundleId: 'com.dcm.dcm.RunnerTests',
  );
}
